### ISSUE TITLE
무중단 배포 구현

### ISSUE THREAD

**Issue by Grara** [Grara/porfol_shop#7]
- `스프링 부트와 AWS로 혼자 구현하는 웹 서비스` 라는 책을 참고했습니다.
- 배포의 전체적인 구조
  - EC2내부에서 애플리케이션 두개가 8081포트와 8082포트를 사용해서 실행됩니다.
  - NginX는 리버스 프록시를 이용해 둘 중 한개의 포트와 연결됩니다.
  - 배포가 진행되면 현재 NginX와 연결되어있지않은 포트로 새로운 애플리케이션이 실행되며, 이후에 NginX는 새로 실행된 애플리케이션의 포트로 연결을 바꿉니다.

    ![image](https://user-images.githubusercontent.com/84609913/209660781-d23a190e-12cb-46ac-9a58-7d66d8072aef.png)

<br>

- 보안과 관련되거나 AWS 웹콘솔을 이용한 설정 부분에 대한 설명은 생략했습니다.
- 보안과 관련된 전체구조는 다음과 같습니다.

    ![image](https://user-images.githubusercontent.com/84609913/209672141-276b783e-5dcc-463b-bf90-04a81107b502.png)

<br>

- 부분 별 구현
- 기본 설정
  - AWS의 EC2서버와 RDS를 준비해줍니다.
  - Travis CI에 들어간 후 GitHub저장소를 연동해줍니다.

<br>

- `TravisCI - AWS S3` 설정
  - 프로젝트내에 .travis.yml을 생성하고 아래와 같이 설정합니다.
    ```yml
    language: java
    jdk: 
    - openjdk11

    branches:
    only:
        - master

    cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.gradle'

    script: "./gradlew clean build"

    notifications:
    email:
        recipients:
        - nomj18@gmail.com

    #배포전 실행할 명령어들
    before_deploy:
    - mkdir -p before-deploy
    - chmod +x scripts/*.sh #모든 sh파일에 실행 권한을 줌
    - cp scripts/*.sh before-deploy/
    - cp appspec.yml before-deploy/
    - cp build/libs/*.jar before-deploy/
    - cd before-deploy && zip -r before-deploy *
    - cd ../ && mkdir -p deploy
    - mv before-deploy/before-deploy.zip deploy/helloshop-webservice.zip


    deploy:
    - provider: s3 #아마존 s3 설정
        access_key_id: $AWS_ACCESS_KEY #AWS IAM 액세스 키
        secret_access_key: $AWS_SECRET_KEY #AWS IAM 비밀 키

        bucket: helloshop-build #s3 버킷이름
        region: ap-northeast-2 #지역
        skip_cleanup: true
        acl: private
        local_dir: deploy
        wait-until-deployed: true

    ```

<br>

- `TravisCI - CodeDeploy` 설정
  - .travis.yml에 아래 내용을 추가해줍니다.
    ```yml
    - provider: codedeploy #아마존 CodeDeploy 설정
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY

        bucket: helloshop-build #s3 버킷이름
        key: helloshop-webservice.zip #전달받을 압축 파일명
        bundle_type: zip
        application: helloshop-webservice #CodeDeploy 애플리케이션명
        deployment_group: helloshop-webservice-group #CodeDeploy 배포그룹명
        region: ap-northeast-2
        wait-until-deployed: true
    ```

<br>

- `CodeDeploy - EC2` 설정
  - EC2에 빌드파일(.jar)과 쉘스크립트파일(.sh)을 인스톨할 위치와 인스톨된 후 실행할 명령을 설정합니다.
  - .appspec.yml에 설정
    ```yml
    version: 0.0
    os: linux
    files:
    - source: /
        destination: /home/ec2-user/app/step3/zip/
        overwrite: yes

    permissions:
    - object: /
        pattern: "**"
        owner: ec2-user
        group: ec2-user

    hooks:
    AfterInstall: #인스톨 직후 stop.sh 실행
        - location: stop.sh
        timeout: 60 #최대 대기시간
        runas: ec2-user

    ApplicationStart: #배포할 애플리케이션을 시작하기위해 start.sh 실행
        - location: start.sh
        timeout: 60
        runas: ec2-user

    #실행 이후 NginX의 연결포트를 방금 실행한 애플리케이션으로 바꾸기 위해 health.sh 실행
    ValidateService: 
        - location: health.sh
        timeout: 60
        runas: ec2-user
    ```

<br>

- 쉘스크립트 파일은 총 5개가 있는데 각각의 역할은 아래와 같습니다.
  - profile.sh : 현재 NginX와 연결되지않은 애플리케이션의 프로파일과 포트를 알아냅니다.
  - stop.sh : 현재 NginX와 연결되지않은 포트로 실행중인 애플리케이션이 있으면 해당 애플리케이션을 종료합니다.
  - start.sh : 배포할 애플리케이션을 NginX와 연결되지않은 포트로 실행합니다.
  - health.sh : 배포할 애플리케이션이 정상적으로 실행됐는지 확인합니다. 이후 NginX를 배포할 애플리케이션의 포트와 연결시킵니다.
  - switch.sh : NginX연결을 바꿔주는 역할 수행, health.sh에서 메소드 사용

<br>
